version: '3'

services:
  postgres:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/

  php-fpm:
    build:
      context: ./docker/php-fpm
    environment:
     - APP_ENV=${APP_ENV}
     - APP_SECRET=${APP_SECRET}
     - DATABASE_URL=postgres://docker:docker@postgres:5432/docker?serverVersion=16&charset=utf8
    volumes:
      - ./:/var/www/
      - ./docker/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./var/logs:/var/log
    depends_on:
      - php-fpm
      - postgres
    ports:
      - "8005:80"